### ISSUE TITLE
Trouble getting everything sorted for first compile.  

### ISSUE THREAD

**Issue by jwtx1980** [LDClark/PlanCheck#2]
First thanks for putting this together. It looks very interesting and I'm excited to see what all you've done.  

Trying to get to where I can compile and run it, I've ran in to some trouble.  I am relatively new to some of this so it maybe that I'm just making beginner type mistakes.   

In any case, I started with a clone of the repository to a local directory using the Git GUI.  

After that I worked through references, most of which I was able to resolve.

However, under plan check reporting - there is a reference for  MigraDoc.RtfRendering.  I have found what I think should go there on Nuget but, am failing to be able to install because of difference in target framework.  V4.5 for the project, something different for the reference.  Any clues here?   

From there it seems like I'm missing, 

Helpers:
\PlanCheck.Script\Helpers\ContourHelper.cs
\PlanCheck.Script\Helpers\DVHExtensions.cs
\PlanCheck.Script\Helpers\HelixToolkitException.cs
\PlanCheck.Script\Helpers\INotifyUserMessaged.cs
\PlanCheck.Script\Helpers\UserMessagedEventArgs.cs
\PlanCheck.Script\Helpers\UserMessager.cs

PNGs:
\PlanCheck.Script\Resources\DoseInValid.png
\PlanCheck.Script\Resources\DoseValid.png
\PlanCheck.Script\Resources\PlanApproved.png
\PlanCheck.Script\Resources\PlanRejected.png
\PlanCheck.Script\Resources\PlanSum.png
\PlanCheck.Script\Resources\PlanUnapproved.png
\PlanCheck.Script\Resources\PlanVerification.png
\PlanCheck.Script\Resources\TreatApproved.png

\PlanCheck.Reporting\packages.config

 \PlanCheck.Runner\Properties\Resources.resx
 \PlanCheck.Runner\App.config 

Any help/ info or guidance would be greatly appreciated.  Again, I can see there was a lot of work here and am excited to see it operate.

**Comment by LDClark** [comment]
The png files are still missing, but the rest should be in there now.  I'm
unable to upload the icons right now, but they are any 16x16 png files that
you want.  There are also png files under Migradoc/Resources for the plan
report that need to be uploaded.  The target framework should be 4.5 for
everything I think, but it should be in Nuget.  Are you using
PDFsharp-MigraDoc 1.50.4619?

**Comment by jwtx1980** [comment]
I was on the latest update of PDF-sharp-MigraDoc.  Rolling back to the one you noted got the references worked out.  

Currently the compiler is looking for two more files.  

Plancheck.runner\Properties\Settings.Designer.cs
Properties\Resources.resx

The complier is not asking for it yet but, I think I may be missing one of the Calculators, CollisionSummariesCalculator.cs?
Properties\AssemblyInfo.cs

**Comment by LDClark** [comment]
All of the files should be in there now.  Let me know how it goes.

Thanks,
Landon

P.S.  I noticed that loaded PlanSums are broken in this version with constraint templates that have [%] constraints.

**Comment by jwtx1980** [comment]
Thanks Landon!  I'll give it a try in the morning.  I'm familiar with the summation % problem.  I have a code I'll share with you tomorrow that tries to address it.  Its built on the dvh metric code as well but has some added features.  Some could be useful.  Thanks again!

**Comment by LDClark** [comment]
Did you fix the % problem?  I'm curious if there is a good way to address it.

Landon

**Comment by LDClark** [comment]
I think I fixed the %dose constraint with plansums, at least for now.  Let me know if anything else isn't working.

**Comment by bilaljalal** [comment]
Hello London
thank you for your lovely work, during compiling, I got the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Warning		There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "VMS.TPS.Common.Model.Types, Version=1.0.200.43, Culture=neutral, PublicKeyToken=305b81e210ec4b89, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	PlanCheck.Runner			
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportStructure.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\Plan.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportPQMs.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\Doctor.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportStructureSet.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportSex.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportData.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportPQM.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportPatient.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\Beam.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportImage.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\ReportPlanningItem.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\Properties\AssemblyInfo.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS2001	Source file 'C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\IReport.cs' could not be found.	PlanCheck.Reporting.MigraDoc	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Reporting.MigraDoc\CSC	1	Active
Error	CS0006	Metadata file 'C:\Users\Bilal\Desktop\plugins\PlanCheck-1.0.0.0.esapi.dll' could not be found	PlanCheck.Runner	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Runner\CSC	1	Active
Error		'Data at the root level is invalid. Line 1, position 1.' XML is not valid.	PlanCheck	C:\Users\Bilal\Desktop\PlanCheck\PlanCheck.Script\MainView.xaml	1	
Warning		Could not resolve this reference. Could not locate the assembly "MigraDoc.RtfRendering, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting			
Warning		Could not resolve this reference. Could not locate the assembly "MigraDoc.Rendering, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting			
Warning		The referenced component 'MigraDoc.RtfRendering' could not be found.	PlanCheck.Reporting			
Warning		The referenced component 'PdfSharp.Charting' could not be found.	PlanCheck.Reporting			
Warning		The referenced component 'PdfSharp' could not be found.	PlanCheck.Reporting			
Warning		The referenced component 'MigraDoc.DocumentObjectModel' could not be found.	PlanCheck.Reporting			
Warning		The referenced component 'MigraDoc.Rendering' could not be found.	PlanCheck.Reporting			
Warning		Could not resolve this reference. Could not locate the assembly "PdfSharp, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting			
Warning		Could not resolve this reference. Could not locate the assembly "MigraDoc.DocumentObjectModel, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting			
Warning		Could not resolve this reference. Could not locate the assembly "PdfSharp.Charting, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting			
Warning		The referenced component 'PdfSharp' could not be found.	PlanCheck.Reporting.MigraDoc			
Warning		Could not resolve this reference. Could not locate the assembly "PdfSharp.Charting, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting.MigraDoc			
Warning		The referenced component 'MigraDoc.Rendering' could not be found.	PlanCheck.Reporting.MigraDoc			
Warning		The referenced component 'MigraDoc.RtfRendering' could not be found.	PlanCheck.Reporting.MigraDoc			
Warning		The referenced component 'MigraDoc.DocumentObjectModel' could not be found.	PlanCheck.Reporting.MigraDoc			
Warning		Could not resolve this reference. Could not locate the assembly "MigraDoc.RtfRendering, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting.MigraDoc			
Warning		The referenced component 'PdfSharp.Charting' could not be found.	PlanCheck.Reporting.MigraDoc			
Warning		Could not resolve this reference. Could not locate the assembly "PdfSharp, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting.MigraDoc			
Warning		Could not resolve this reference. Could not locate the assembly "MigraDoc.Rendering, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting.MigraDoc			
Warning		Could not resolve this reference. Could not locate the assembly "MigraDoc.DocumentObjectModel, Version=1.50.4619.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Reporting.MigraDoc			
Warning		The referenced component 'YamlDotNet' could not be found.	PlanCheck			
Warning		There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "VMS.TPS.Common.Model.Types, Version=1.0.200.43, Culture=neutral, PublicKeyToken=305b81e210ec4b89, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "GalaSoft.MvvmLight, Version=5.3.0.19026, Culture=neutral, PublicKeyToken=e7570ab207bcb616, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "YamlDotNet, Version=3.9.0.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "GalaSoft.MvvmLight.Platform, Version=5.3.0.19032, Culture=neutral, PublicKeyToken=5f873c45e98af8a1, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck			
Warning		The referenced component 'System.Windows.Interactivity' could not be found.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "GalaSoft.MvvmLight.Extras, Version=5.3.0.19032, Culture=neutral, PublicKeyToken=669f0b5e8f868abf, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck			
Warning		The referenced component 'GalaSoft.MvvmLight.Extras' could not be found.	PlanCheck			
Warning		There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "VMS.TPS.Common.Model.API, Version=1.0.200.43, Culture=neutral, PublicKeyToken=305b81e210ec4b89, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	PlanCheck			
Warning		The referenced component 'GalaSoft.MvvmLight.Platform' could not be found.	PlanCheck			
Warning		The referenced component 'GalaSoft.MvvmLight' could not be found.	PlanCheck			
Warning		The referenced component 'Microsoft.Practices.ServiceLocation' could not be found.	PlanCheck			
Warning		The referenced component 'EclipsePlugInRunner' could not be found.	PlanCheck			
Warning		A custom tool 'ResXFileCodeGenerator' is associated with file 'Properties\Resources.resx', but the output of the custom tool was not found in the project.  You may try re-running the custom tool by right-clicking on the file in the Solution Explorer and choosing Run Custom Tool.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "EclipsePlugInRunner, Version=2.0.0.0, Culture=neutral, processorArchitecture=AMD64". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck			
Warning		No way to resolve conflict between "PlanCheck.Reporting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" and "PlanCheck.Reporting". Choosing "PlanCheck.Reporting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily.	PlanCheck			
Warning		Could not resolve this reference. Could not locate the assembly "GalaSoft.MvvmLight, Version=5.3.0.19026, Culture=neutral, PublicKeyToken=e7570ab207bcb616, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Runner			
Warning		The referenced component 'YamlDotNet' could not be found.	PlanCheck.Runner			
Warning		Could not resolve this reference. Could not locate the assembly "System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Runner			
Warning		The referenced component 'GalaSoft.MvvmLight.Platform' could not be found.	PlanCheck.Runner			
Warning		Could not resolve this reference. Could not locate the assembly "GalaSoft.MvvmLight.Extras, Version=5.3.0.19032, Culture=neutral, PublicKeyToken=669f0b5e8f868abf, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Runner			
Warning		The referenced component 'EclipsePlugInRunner' could not be found.	PlanCheck.Runner			
Warning		Could not resolve this reference. Could not locate the assembly "EclipsePlugInRunner, Version=2.0.0.0, Culture=neutral, processorArchitecture=AMD64". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Runner			
Warning		The referenced component 'Microsoft.Practices.ServiceLocation' could not be found.	PlanCheck.Runner			
Warning		The referenced component 'GalaSoft.MvvmLight.Extras' could not be found.	PlanCheck.Runner			
Warning		There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "VMS.TPS.Common.Model.API, Version=1.0.200.43, Culture=neutral, PublicKeyToken=305b81e210ec4b89, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	PlanCheck.Runner			
Warning		Could not resolve this reference. Could not locate the assembly "GalaSoft.MvvmLight.Platform, Version=5.3.0.19032, Culture=neutral, PublicKeyToken=5f873c45e98af8a1, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Runner			
Warning		The referenced component 'GalaSoft.MvvmLight' could not be found.	PlanCheck.Runner			
Warning		The referenced component 'System.Windows.Interactivity' could not be found.	PlanCheck.Runner			
Warning		Could not resolve this reference. Could not locate the assembly "Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Runner			
Warning		Could not resolve this reference. Could not locate the assembly "YamlDotNet, Version=3.9.0.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	PlanCheck.Runner

**Comment by LDClark** [comment]
I made some changes to the repository.  You still might have some problems but they should be fixable:
1.) Make sure the configuration manager has x64 for the Platform on all projects
2.)  Right click solution, Manage Nuget Packages..., and restore the packages.  You might also have to manually delete the migradoc references and nuget install PDFSharp-Migradoc to get them back.

**Comment by bilaljalal** [comment]
Thank you very much for your input , eveything looks working fine now, I have a question please,
if I want to change the color for the **Goal/ Variation/ Not Met** constrains in the generated PDF file such that; ( Goal in Green, Variation in Yellow, Not Met in Red) . can you please explain what to do?

**Comment by LDClark** [comment]
I believe that could be added in PlanCheck.Reporting.MigraDoc/Internal/PQMsContent.cs.

You could do something similar to AlternateRowShading() method, but instead of row color, changing font color maybe?  There could be an if statement on the goal/variation/not met and change it to the desired color.

**Comment by bilaljalal** [comment]
Hello, I would like to make print for the Plan Check "PC" list
how to do that, I tried to follow how you make the print for PQM but I failed to do that, so can you please tell me how the print pdf file get the data and then generate the pdf, I mean where to make changes to have PC also part of the generated report
