### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by yograjyog** [LDClark/PlanCheck#4]
Dear Landon, Came across ur script, as i am novice to eclipse scripting, would you plz let me know how to utiliize it in an Eclipse 15.6 environment. Thanks in advance.

Yoga D

**Comment by LDClark** [comment]
I would like to some day write a guide, and also release prebuilt .dlls for
the script for every eclipse version.

Right now, the only way to run it is to download the source files and
rebuild it.  If you have 15.6 dlls you can attach those in the references.
15.6 hopefully is very similar to 15.5, so not much (if any) code would
need to be changed.

**Comment by yograjyog** [comment]
While building it I am having this warnings. How can I fix this?
![How can i solve]

(https://user-images.githubusercontent.com/17076501/68081058-ac58e080-fe2d-11e9-8015-385a52564eb9.PNG)
