### ISSUE TITLE
Script is running but the Browser is not opening

### ISSUE THREAD

**Issue by angelikay** [LDClark/PlanCheck#8]
Dear Landon, 
I hope everything is well with you. I was trying to run your PlanCheck scripts but when I run it, the script seems to be running on the background without any error but there are no browser or any dialog box that is opening. Kindly advice. Thank you.

**Comment by LDClark** [comment]
What type of plan are you running it on?  Does it have a structure set and valid dose?  

I did find that plans without structure sets crash the script, but it is updated now.

Are you able to run from visual studio on a nonclinical box?

Landon

**Comment by angelikay** [comment]
Dear Landon,

Thank you for your reply. It is Rapidarc Plan brain patient. Yes, it has structure set and dose. I am trying to run it in TBOX but nothing is poppinh out, it seems running in the backgound that makes the system to freeze.


Sent from my iPhone

On 28 Sep 2022, at 7:18 AM, Landon Clark ***@***.***> wrote:

﻿

What type of plan are you running it on? Does it have a structure set and valid dose?

I did find that plans without structure sets crash the script, but it is updated now.

Are you able to run from visual studio on a nonclinical box?

Landon

**Comment by LDClark** [comment]
Interesting, it shouldn't have any issues with that plan.  Are there any
other plans in this patient (even in other courses)?  When it first runs,
it goes through all the plans, and it could be crashing on one of those
plans.

For troubleshooting, would you be able to run on another patient (ideally
one with a single plan, with valid dose, and a structure set)?

Also, if you want to troubleshoot in Visual Studio, you can click Start at
the top and it will run EsapiEssentials though the PlanCheck.Runner.  That
should give you more details on the exception.  It might take a few more
minutes that way though.

I'm sure it's something small that is crashing it.  If we can find the
source, I can update the repository.

Thanks!

**Comment by LDClark** [comment]
Also to double check, if you are running from the Tools>Scripts in Eclipse, did you copy over all dlls to the running folder?  There should also be a ConstraintTemplates folder in the same directory (usually the PublishedScripts folder).

**Comment by LDClark** [comment]
I think I'm getting the same problem now.  I should be able to find out why its not running, and will update this week.

**Comment by LDClark** [comment]
Try the new version that is out now.  The issue was with recent changes to the MainWindow.xaml.  It should be working as a plugin script now.

**Comment by angelikay** [comment]
It is now working. Thank you so much for this great scripts. Just regarding the print to PDF, it does not print and makes the system freeze.
With regards to the Collision checks. We created a wrong plan to see how the script will work. But it didn’t show any status & Gantry to table distance. Please see screenshot below.

***@***.***

Lastly, on the PQM Achieved column it shows a bar chart. Kindly let me know what it means?
Thank you for your help and support.

**Comment by LDClark** [comment]
I'm wondering if the temp file location is the issue, for saving the PDFs.  It might be possible in the future to move the reports to a folder in the scripts directory.  Are you running through citrix or though a thick client?

I can't see the screenshot.  Did your plan have a structure called CouchSurface?  If not, what was the couch structure called?  It might be having a problem with the table location.

The Achieved column has a progress bar across the cells.  That is the ratio of achieved/goal.  e.g. If the goal is 6000 and the achieved is 3000, it should be halfway across the cell.  You could remove the ProgressBar from the MainWindow.xaml, and that would remove the colored bars.

**Comment by angelikay** [comment]
﻿We are running through client, not on citrix. Will the PDF print be affected because of that?
There is no couch on the plan. We just added a couch and now it is fine.
Great, I have manage to worked on the MainWindow.xaml. Thank you so much.


On 29 Sep 2022, at 9:00 PM, Landon Clark ***@***.***> wrote:

﻿

I'm wondering if the temp file location is the issue, for saving the PDFs. It might be possible in the future to move the reports to a folder in the scripts directory. Are you running through citrix or though a thick client?

I can't see the screenshot. Did your plan have a structure called CouchSurface? If not, what was the couch structure called? It might be having a problem with the table location.

The Achieved column has a progress bar across the cells. That is the ratio of achieved/goal. e.g. If the goal is 6000 and the achieved is 3000, it should be halfway across the cell. You could remove the ProgressBar from the MainWindow.xaml, and that would remove the colored bars.

**Comment by LDClark** [comment]
Citrix should work with everything.  I'll look some more into it to see why
PDFs are not working in your case.

**Comment by angelikay** [comment]
Thank you so much appreciated.
There is also a problem with the Achieved for Dcc objective they are all unable to calculate and not evaluated.

Sent from my iPhone

On 3 Oct 2022, at 8:31 PM, Landon Clark ***@***.***> wrote:

﻿

Citrix should work with everything. I'll look some more into it to see why
PDFs are not working in your case.

**Comment by LDClark** [comment]
Are you using Gy or cGy for a dose unit in External Beam, and also which
units for the constraint template?  Are there any details after "Unable to
calculate", or is that all it says?

Also could you send me the:
-volume of the structure
-objective (e.g. D0.5cc[cGy])
-goal (e.g. 3600)
-expected achieved if possible

Thanks for the feedback!

**Comment by angelikay** [comment]
We are using your conventional fractionation template. It is okay now, I am not getting the unable to calculate and evaluate anymore. I have changed all from cGy to Gy. Thanks a lot.

Sent from my iPhone

On 4 Oct 2022, at 5:46 PM, Landon Clark ***@***.***> wrote:

﻿

Are you using Gy or cGy for a dose unit in External Beam, and also which
units for the constraint template? Are there any details after "Unable to
calculate", or is that all it says?

Also could you send me the:
-volume of the structure
-objective (e.g. D0.5cc[cGy])
-goal (e.g. 3600)
-expected achieved if possible

Thanks for the feedback!

**Comment by LDClark** [comment]
I made a change that hopefully will work for sites that use Gy or cGy.  It will check the constraint templates units, and update the PQMs to match, if they are mismatching.  Thankfully I can troubleshoot using both units.

**Comment by LDClark** [comment]
I'm going to close this ticket out.  Let me know if you have any other problems!
