### ISSUE TITLE
PQM ID Aliases not consistently working

### ISSUE THREAD

**Issue by gbaltz** [LDClark/PlanCheck#9]
Hi,
Lack of standardization is the bane of all our existence. I'm trying to use the ID Alias feature in the PQM templates, and it seems like it works for some structures and not for others.

For example it is able to successfully associate the alias "Aorta" for "GreatVessels", but it's not able to associate alias "PTV" for "PTV_5000". Or associate alias "LungsMinusGTV" for "LungsMinusITV".

**Comment by LDClark** [comment]
I definitely agree with you, and have gone back and forth on the best way to implement it.  I think there is a trade off of finding all possible matching structures in the list, and possibly getting duplicates.  The LungsMinusITV could show up by its structure ID, its alias LungsMinusGTV structure ID, or its structure code 68877.

It might be possible to make the for loops better, or to filter out the duplicates at the end.  I'll look at it some more this week.

Thanks!

**Comment by LDClark** [comment]
There are some new for loops in the new version.  Could you let me know if that helps alias matching?

**Comment by gbaltz** [comment]
Hey, sorry for the delay. I tried it out and it seems like the alias matching is catching everything now! Thanks for the update!

**Comment by LDClark** [comment]
Good to hear!  Thanks for letting me know.
